import type {
  CategoryFilter,
  CompanySizeFilter,
  WorkTypeFilter,
} from "@/config/job-seeker-search-filters";
import {
  enrichJobSearchResult,
  type JobSeekerSearchResultCore,
  type JobSeekerSearchResultEnriched,
} from "@/config/job-seeker-search-enrichment";

export type { JobSeekerSearchResultCore };
export type JobSeekerSearchResult = JobSeekerSearchResultEnriched;

/** Results per page on the search screen. */
export const JOB_SEEKER_SEARCH_PAGE_SIZE = 4;

export function getJobSeekerSearchResult(id: string) {
  return jobSeekerSearchResults.find((job) => job.id === id);
}

/** Placeholder results — replace with API data later. */
const jobSeekerSearchResultsCore: JobSeekerSearchResultCore[] = [
  {
    id: "1",
    jobTitle: "Senior Product Designer",
    companyName: "Northwind Labs",
    companyMeta: "SaaS · 120–250 employees",
    salaryRange: "$140k–$175k",
    location: "Remote (US & Canada)",
    employmentType: "Full-time",
    experience: "5+ years",
    description:
      "Own end-to-end UX for workflow automation used by 40k+ B2B users. Partner with PM and engineering on discovery, prototyping, and QA. You will extend the design system, run usability tests, and ship features on a two-week cadence.",
    highlights: [
      "Figma, design tokens, and component libraries required",
      "Equity, $4k learning stipend, and 4-day summer weeks",
    ],
    rating: 4.6,
    reviewCount: 128,
    tags: ["Remote", "Design"],
    workTypes: ["remote"],
    categories: ["design", "product"],
    companySize: "mid",
  },
  {
    id: "2",
    jobTitle: "Senior Product Manager",
    companyName: "Brightline Health",
    companyMeta: "Healthcare · Series C",
    salaryRange: "$155k–$190k",
    location: "Boston, MA · Hybrid (3 days on-site)",
    employmentType: "Full-time",
    experience: "6+ years",
    description:
      "Lead the patient portal roadmap across web and mobile, from intake through care plans. Define metrics with clinical ops, prioritize HIPAA-compliant releases, and align stakeholders across engineering, design, and compliance.",
    highlights: [
      "Healthcare or regulated-industry PM experience preferred",
      "Medical, dental, vision, and mental health benefits from day one",
    ],
    rating: 4.2,
    reviewCount: 84,
    tags: ["Hybrid", "Product"],
    workTypes: ["hybrid"],
    categories: ["product", "engineering"],
    companySize: "mid",
  },
  {
    id: "3",
    jobTitle: "Embedded Software Engineer",
    companyName: "Atlas Mobility",
    companyMeta: "Automotive · Global",
    salaryRange: "$130k–$165k",
    location: "Detroit, MI · On-site",
    employmentType: "Full-time",
    experience: "4+ years",
    description:
      "Build C/C++ firmware and middleware for fleet telematics and in-vehicle displays. Work with hardware teams on bring-up, diagnostics, and OTA updates for enterprise OEM partners.",
    highlights: [
      "RTOS, CAN bus, and embedded Linux experience required",
      "Relocation package and on-site EV charging",
    ],
    rating: 4.8,
    reviewCount: 203,
    tags: ["On-site", "Engineering"],
    workTypes: ["onsite"],
    categories: ["engineering"],
    companySize: "enterprise",
  },
  {
    id: "4",
    jobTitle: "Brand Designer",
    companyName: "Paper & Pixel",
    companyMeta: "Agency · Creative",
    salaryRange: "$85k–$110k",
    location: "Remote · US time zones",
    employmentType: "Full-time",
    experience: "3+ years",
    description:
      "Design brand identities, marketing sites, and campaign assets for fintech and health clients. Present concepts to client stakeholders, maintain brand guidelines, and collaborate with copywriters and developers on handoff.",
    highlights: [
      "Strong typography and motion-ready layout skills",
      "Flexible hours and project bonus pool",
    ],
    rating: 4.4,
    reviewCount: 56,
    tags: ["Remote", "Brand"],
    workTypes: ["remote", "hybrid"],
    categories: ["design", "marketing"],
    companySize: "startup",
  },
  {
    id: "5",
    jobTitle: "Operations Analyst",
    companyName: "Summit Finance",
    companyMeta: "Fintech · 500+ employees",
    salaryRange: "$95k–$120k",
    location: "New York, NY · Hybrid",
    employmentType: "Full-time",
    experience: "2–4 years",
    description:
      "Analyze onboarding funnel data, document SOPs for risk and compliance, and support tooling migrations. Partner with product on KPI dashboards and weekly ops reviews with leadership.",
    highlights: [
      "SQL, Excel, and process mapping experience required",
      "401(k) match and annual bonus eligible",
    ],
    rating: 4.1,
    reviewCount: 312,
    tags: ["Hybrid", "Operations"],
    workTypes: ["hybrid", "onsite"],
    categories: ["operations", "product"],
    companySize: "enterprise",
  },
  {
    id: "6",
    jobTitle: "Frontend Engineer",
    companyName: "Lumen Grid",
    companyMeta: "Energy · Series B",
    salaryRange: "$125k–$155k",
    location: "Remote (EU & UK)",
    employmentType: "Full-time",
    experience: "3+ years",
    description:
      "Ship React dashboards for utility partners monitoring grid load and renewables. Integrate real-time APIs, optimize chart performance, and contribute to shared UI libraries with design and data teams.",
    highlights: [
      "TypeScript, React, and data-viz libraries (D3 or Recharts)",
      "Climate stipend and co-working budget",
    ],
    rating: 4.5,
    reviewCount: 67,
    tags: ["Remote", "Engineering"],
    workTypes: ["remote"],
    categories: ["engineering", "product"],
    companySize: "startup",
  },
  {
    id: "7",
    jobTitle: "Growth Marketing Manager",
    companyName: "Harbor & Co.",
    companyMeta: "Retail · E-commerce",
    salaryRange: "$100k–$130k",
    location: "Amsterdam · Hybrid",
    employmentType: "Full-time",
    experience: "4+ years",
    description:
      "Own paid and lifecycle campaigns for DTC brands entering EU markets. Run A/B tests on email and paid social, manage agency partners, and report CAC and LTV weekly to brand leads.",
    highlights: [
      "Meta Ads, Klaviyo, and GA4 proficiency required",
      "Travel allowance for market visits twice per year",
    ],
    rating: 4.3,
    reviewCount: 91,
    tags: ["Hybrid", "Marketing"],
    workTypes: ["hybrid"],
    categories: ["marketing"],
    companySize: "mid",
  },
  {
    id: "8",
    jobTitle: "Embedded Systems Engineer",
    companyName: "Vertex Robotics",
    companyMeta: "Hardware · R&D",
    salaryRange: "$135k–$170k",
    location: "Pittsburgh, PA · On-site",
    employmentType: "Full-time",
    experience: "5+ years",
    description:
      "Develop control software for industrial robotic arms and safety systems. Prototype on lab hardware, write unit tests for motion planning, and document APIs for field deployment teams.",
    highlights: [
      "C++, Python, and motor control experience required",
      "Lab access and conference budget",
    ],
    rating: 4.7,
    reviewCount: 44,
    tags: ["On-site", "Engineering"],
    workTypes: ["onsite"],
    categories: ["engineering"],
    companySize: "mid",
  },
  {
    id: "9",
    jobTitle: "Product Manager, Legal Ops",
    companyName: "Cedar Legal",
    companyMeta: "Legal tech · 80 employees",
    salaryRange: "$120k–$145k",
    location: "Remote (US)",
    employmentType: "Full-time",
    experience: "4+ years",
    description:
      "Define roadmap for contract review and approval workflows used by in-house legal teams. Gather requirements from enterprise customers, write specs for engineering, and measure adoption and time-to-sign.",
    highlights: [
      "B2B SaaS PM experience; legal domain a plus",
      "Unlimited PTO and home office setup stipend",
    ],
    rating: 4.0,
    reviewCount: 38,
    tags: ["Remote", "Product"],
    workTypes: ["remote", "hybrid"],
    categories: ["product", "operations"],
    companySize: "startup",
  },
  {
    id: "10",
    jobTitle: "Customer Experience Specialist",
    companyName: "Orbit Airlines",
    companyMeta: "Travel · Global",
    salaryRange: "$58k–$72k",
    location: "Dallas, TX · Hybrid",
    employmentType: "Full-time",
    experience: "2+ years",
    description:
      "Improve booking, loyalty, and support journeys across web and contact center tools. Map pain points, propose process fixes with ops, and track NPS and resolution time after each release.",
    highlights: [
      "CX or hospitality background; GDS knowledge a plus",
      "Flight benefits and shift flexibility",
    ],
    rating: 4.2,
    reviewCount: 276,
    tags: ["Hybrid", "Operations"],
    workTypes: ["hybrid", "onsite"],
    categories: ["operations", "product"],
    companySize: "enterprise",
  },
  {
    id: "11",
    jobTitle: "Product Designer",
    companyName: "Studio Kite",
    companyMeta: "Design agency · Boutique",
    salaryRange: "$90k–$115k",
    location: "Remote · Global",
    employmentType: "Full-time",
    experience: "3+ years",
    description:
      "Ship brand systems and product UI for seed-stage startups on 8–12 week engagements. Run discovery workshops, deliver hi-fi prototypes in Figma, and support dev handoff with annotated specs.",
    highlights: [
      "Portfolio with shipped web or mobile products",
      "Async-first culture and profit-sharing",
    ],
    rating: 4.9,
    reviewCount: 29,
    tags: ["Remote", "Design"],
    workTypes: ["remote"],
    categories: ["design"],
    companySize: "startup",
  },
  {
    id: "12",
    jobTitle: "Data Visualization Designer",
    companyName: "Pulse Analytics",
    companyMeta: "Data · SaaS",
    salaryRange: "$115k–$140k",
    location: "Remote (US)",
    employmentType: "Full-time",
    experience: "4+ years",
    description:
      "Design charts, dashboards, and narrative reports for B2B analytics customers. Partner with frontend engineers on accessible color systems, responsive layouts, and design QA on production data.",
    highlights: [
      "Complex data UI portfolio; SQL literacy helpful",
      "Equity and parental leave at 12 months",
    ],
    rating: 4.4,
    reviewCount: 112,
    tags: ["Remote", "Engineering"],
    workTypes: ["remote"],
    categories: ["engineering", "design"],
    companySize: "mid",
  },
  {
    id: "13",
    jobTitle: "Regulatory Operations Coordinator",
    companyName: "Greenfield Bio",
    companyMeta: "Biotech · Research",
    salaryRange: "$70k–$88k",
    location: "Cambridge, MA · On-site",
    employmentType: "Full-time",
    experience: "1–3 years",
    description:
      "Coordinate submissions and document control for clinical trial phases. Track deadlines with regulatory affairs, maintain audit-ready files, and support science communications with templated reports.",
    highlights: [
      "Life sciences or compliance admin experience preferred",
      "Tuition reimbursement for relevant certifications",
    ],
    rating: 3.9,
    reviewCount: 52,
    tags: ["On-site", "Operations"],
    workTypes: ["onsite"],
    categories: ["operations"],
    companySize: "enterprise",
  },
  {
    id: "14",
    jobTitle: "Editorial Product Manager",
    companyName: "Relay Media",
    companyMeta: "Media · Publishing",
    salaryRange: "$110k–$135k",
    location: "London, UK · Hybrid",
    employmentType: "Full-time",
    experience: "5+ years",
    description:
      "Own subscription paywall, newsletter tools, and reader apps for a national publisher. Prioritize experiments with editorial and growth, and define success metrics for retention and conversion.",
    highlights: [
      "Media or consumer subscription product experience",
      "Press club membership and flexible Fridays",
    ],
    rating: 4.1,
    reviewCount: 73,
    tags: ["Hybrid", "Product"],
    workTypes: ["hybrid"],
    categories: ["product", "marketing"],
    companySize: "mid",
  },
  {
    id: "15",
    jobTitle: "Security Engineer",
    companyName: "Forge Security",
    companyMeta: "Cybersecurity · Series C",
    salaryRange: "$150k–$185k",
    location: "Remote (US & EU)",
    employmentType: "Full-time",
    experience: "5+ years",
    description:
      "Harden enterprise threat detection pipelines, review architecture for new features, and respond to incidents with SRE and customer success. Automate detection rules and contribute to security runbooks.",
    highlights: [
      "Cloud security (AWS/GCP), SIEM, and scripting required",
      "On-call compensation and certification budget",
    ],
    rating: 4.6,
    reviewCount: 156,
    tags: ["Remote", "Engineering"],
    workTypes: ["remote", "hybrid"],
    categories: ["engineering"],
    companySize: "mid",
  },
  {
    id: "16",
    jobTitle: "Curriculum Designer",
    companyName: "Nest Education",
    companyMeta: "EdTech · 200 employees",
    salaryRange: "$80k–$100k",
    location: "Remote (US)",
    employmentType: "Full-time",
    experience: "3+ years",
    description:
      "Build K–12 math and science modules aligned to state standards. Write learning objectives, storyboard interactives with product design, and pilot content with district partners before scale-up.",
    highlights: [
      "Instructional design or classroom teaching background",
      "Summer break shutdown and learning stipend",
    ],
    rating: 4.3,
    reviewCount: 98,
    tags: ["Remote", "Design"],
    workTypes: ["remote"],
    categories: ["design", "product"],
    companySize: "mid",
  },
];

export const jobSeekerSearchResults: JobSeekerSearchResult[] =
  jobSeekerSearchResultsCore.map(enrichJobSearchResult);
